### ISSUE TITLE
Network adapter disappear

### ISSUE THREAD

**Issue by arpsyapathy** [Mieze/RTL8111_driver_for_OS_X#20]
Hello all!

Help with solving the problem please!
I have RTL8111. 
The Mieze kext works, BUT:
After the computer restarts, the adapter disappears from the system, is missing from the system information, and therefore there is no network.
That most strange! In Windows he, too, deaf! That is, in fact as if there is no network adapter.
But the link indicator is lit))

When I reset BIOS and I include the device - the adapter appears again.

Any ideas comrades? Thanks in advance!

**Comment by Mieze** [comment]
Most likely a BIOS issue and I doubt that it has anything to do with the driver unless your machine has unusual hardware configuration. There is nothing I can do for you!
