### ISSUE TITLE
RTL8111H not working with Catalina?

### ISSUE THREAD

**Issue by Oscar7601** [Mieze/RTL8111_driver_for_OS_X#24]
Hello,
I am trying to install Catalina on a new computer. However, I would need my Realtek 8111H to work to install Catalina. But I cannot find a kext which makes the NIC work.
Could you please provide an updated kext for Catalina for my NIC?
Thank you in advance!

**Comment by Mieze** [comment]
No, I won't because there is no need for an update. The driver works fine with Catalina, I verified it personally. If it doesn't work for, search for another reason but the driver itself is definitely not the responsible.

**Comment by Oscar7601** [comment]
Hello again Mieze and thank you for your quick reply. I will then search for this other reason.
