### ISSUE TITLE
No internet on Catalina recovery install 

### ISSUE THREAD

**Issue by eyalmazuz** [Mieze/RTL8111_driver_for_OS_X#25]
I'm trying to Install macOS Catalina
and I'm using the kext, on Mojave half a year ago, everything worked fine
now when I'm trying to use Catalina I'm getting a weird IP address

![JPEG_20191205_165741](https://user-images.githubusercontent.com/34383384/70248717-024dda80-1784-11ea-85fe-8cf9f9d5c031.jpg)

lscpi on Linux returns that it's RTL8111 and it's the kext I've used for Mojave

pc specs:
Intel i5-4670
Gigabyte GA-B85M-HD3
16gb ddr3 1666mhz ram
Gigabyte Gefore 770GTX

I'm using clover version 5092 with the following kexts:
VirtualSMC
Lilu
WhateverGreen
USBInjectAll
RTL8111
AppleALC

this is my config.plist (converted to txt cause github doesn't support plist..)
[config.plist](https://github.com/Mieze/RTL8111_driver_for_OS_X/files/3927636/config.txt)

**Comment by pradorocchi** [comment]
It's a bug with Clover. Just needed to change **OSBundleRequired** from **Network-Root** to **Root** inside the Info.plist file located within the kext.
