### ISSUE TITLE
not working on MSI Z370-A

### ISSUE THREAD

**Issue by waini1110** [Mieze/RTL8111_driver_for_OS_X#28]
Thanks for your driver. 
MSI Z370-A using RTL8111H Gigabit,
 OS : 10.15.4.
 Opencore : 0.5.9
The 2.3.0d10 not working on MSI Z370-A, but 2.3.0d07 is working fine.
if possible, could you please check it? 
if you need more error informations, please let me know how to check. 

Thanks again.

**Comment by khoahoc0508** [comment]
I have same problem too. Please help. Thanks !
@waini1110 can you send me efi efi folder ? i used to Clover all the time and now want to try OpenCore.

**Comment by Mieze** [comment]
According to your problem description I'm almost 100% sure that this is another case of PEBKAC. Please fix your system because the driver is not the problem.

**Comment by waini1110** [comment]
@Mieze  Thanks for your reply, When I changed from automatic configuration to manual configuration in network settings and forced it to 100M, it started working.
I'm sorry to bother you, have a nice day. 

I will close this issue. 

Thanks again.
