### ISSUE TITLE
returns to WORKGROUP

### ISSUE THREAD

**Issue by popowsergei** [Mieze/RTL8111_driver_for_OS_X#29]
it is not possible to change the working group. changes are not saved and returns to WORKGROUP

**Comment by popowsergei** [comment]
10.14.6 18G4032 B85M-D3H

**Comment by Mieze** [comment]
This is not a driver issue! A driver handles packets, nothing more and nothing less.

**Comment by popowsergei** [comment]
where to look ? where to find the problem ?

**Comment by Mieze** [comment]
Ask Apple!
