### ISSUE TITLE
Version 2.3.0d10 and RTL8168H not working with direct laptop-device connection

### ISSUE THREAD

**Issue by FreeJHack** [Mieze/RTL8111_driver_for_OS_X#31]
Hi,
Version 2.3.0d10 installed on Mojave 10.14.6 (18G4032) with RTL8168H is not working with direct connections.
I mean, it correctly works with hub/switch on a network but connecting a device directly it does not work. No green led, no orange led, (PM issue?) both device's led remain off, as per cable not connected.
ASPM property is YES (disabled) as per default settings.
No problem with current release version 2.2.2.

**Comment by Mieze** [comment]
I assume that it's a firmware issue which is far beyond my scope.
