### ISSUE TITLE
after sleep it doesn't work

### ISSUE THREAD

**Issue by asgmeonerandom** [Mieze/RTL8111_driver_for_OS_X#32]
hi,

do you know what can i do to troubleshoot?

on network settings it says not plugged.
I tried ifconfig en0 down` then `ifconfig en0 up`
kextstat show realtek.
I am out of ideas other than reinstaling .

thanks in advance

**Comment by Mieze** [comment]
I gave detailed troubleshooting information in the driver's thread on insanelymac.com.
