### ISSUE TITLE
Ethernet cable unplugged after updating. works fine with old version.

### ISSUE THREAD

**Issue by siddharthbiju** [Mieze/RTL8111_driver_for_OS_X#36]
Ethernet not connected with error message " cable unplugged " after updating. Ethernet works fine with 2.2.2 release.
![Screenshot 2020-08-27 at 10 18 14 PM](https://user-images.githubusercontent.com/52505665/91471291-7cdefd00-e8b3-11ea-94ab-0cf87b549372.png)

**Comment by Mieze** [comment]
Please refer to the driver's thread on insanelymac.com

https://www.insanelymac.com/forum/topic/287161-new-driver-for-realtek-rtl8111/

in case you have further questions, need support or want to submit a problem report. Support requests here on Github will be ignored!
