### ISSUE TITLE
IOPCIDevice' is deprecated

### ISSUE THREAD

**Issue by iMonZ** [Mieze/RTL8111_driver_for_OS_X#37]
Hey, is it possible to fix this warning?
`'IOPCIDevice' is deprecated: Use PCIDriverKit`

And how heavy is the implementation of the DriverKit?
Apple said this is very easy 
Is that true?

**Comment by Mieze** [comment]
I have no intentions to "fix" this because I don't see it as an issue. This driver will stay inside inside kernel space as long as there is a way to create 3rd-party kernel extensions and in case Apple may lock us out one day, it'll be obsolete because it will be the end of hackintoshing anyway.
