### ISSUE TITLE
dont work on big sur

### ISSUE THREAD

**Issue by amervelic** [Mieze/RTL8111_driver_for_OS_X#38]
Version 2.3.0 (Big Sur Beta 6) does not work, MB: Asus prime b250m-k but it works with [rehabman](https://bitbucket.org/RehabMan/os-x-realtek-network/downloads/) when macOS boot , disable LAN network.

**Comment by amervelic** [comment]
[rehabman](https://bitbucket.org/RehabMan/os-x-realtek-network/downloads)

**Comment by Mieze** [comment]
PEBCAK!
