### ISSUE TITLE
Realtek 8118 Gaming no ethernet on V2.3.0

### ISSUE THREAD

**Issue by qyzdo** [Mieze/RTL8111_driver_for_OS_X#40]
Hello, I upgraded kext from V2.2.2 to V2.3.0 on my Realtek 8118 Gaming on Gigabyte Z390 UD and ethernet stopped working. It was showing no connection all the time, I spent few hours to figure what is going on, because I was also updating opencore and when I finally downgraded kext to V2.2.2 everything started working again. 

It was also clean install of newest macOS.

**Comment by Mieze** [comment]
In case you need help, you should give me a little bit more information because I'm not a clairvoyant. Have you checked the kernel logs or did you spent these hours smoking dope and drinking wine?

**Comment by qyzdo** [comment]
I tought it was opencore fault so I was just switching different files and hoping that it will work, then I switched this kext and it started working without problems. I can replace this kext again with the newest version and check everything for you, but you need to tell me how to check logs and other stuff which will tell you more information :)

**Comment by Mieze** [comment]
You'll find detailed instructions in post#1 of the driver's thread on insanelymac.com.
