### ISSUE TITLE
My Windows can't access to the network adapter after using this kext.

### ISSUE THREAD

**Issue by yikchunnnn** [Mieze/RTL8111_driver_for_OS_X#41]
My Device Manger in Windows shows a yellow exclamation mark and an error code 'This device cannot start. (Code 10)'
I've tried booting only with the Windows drive, and updated the BIOS.
But Windows still can't access to the network adapter.
My MB is msi B450M Mortar Max

**Comment by Mieze** [comment]
Off-topic!
