### ISSUE TITLE
RTL8111H not working #2.3.0

### ISSUE THREAD

**Issue by SonerOd** [Mieze/RTL8111_driver_for_OS_X#45]
Ethernet is seen on System prefrences but It says cable is not connected. When I trying on windows, it's working properly.

Note: I've Big Sur Beta.

**Comment by King-stark** [comment]
I ran into the same problem when I tried to replace from 2.2.2 to 2.3.0.

**Comment by King-stark** [comment]
> I ran into the same problem when I tried to replace from 2.2.2 to 2.3.0.
The 2.3.0 driver has been loaded, but the Ethernet en0 interface cannot detect my network access (my environment is big sur beta 9)

**Comment by SonerOd** [comment]
I'm back to 2.2.2 now it works. but not working with 2.3.0. Issue is not solved.

**Comment by Mieze** [comment]
As nobody has provided any information about what might be wrong, I assume that these are cases of PEBKAC. I'm not a full service provider!
