### ISSUE TITLE
 RTL8111H not working on v2.3.0

### ISSUE THREAD

**Issue by yahia20** [Mieze/RTL8111_driver_for_OS_X#46]
I have the b450 asrock steel legend and the new version doesn't work. v2.2.2 works fine.
I don't know what the issue is. for the mean time I will use v2.2.2. I haven't installed catalina yet (It doesn't work in the installer don't know what it will do after install) .

**Comment by Mieze** [comment]
> I don't know what the issue is.

Let me guess: PEBCAK?

Refer to the driver's thread on insanelymac.com for support!
