### ISSUE TITLE
RTL8111/8168B not working with 2.3.0

### ISSUE THREAD

**Issue by egar3427** [Mieze/RTL8111_driver_for_OS_X#47]
The ethernet keep bouncing between connected and disconnected. And then I turn of EEE in the kext info.plist. its working normally. This is not the case before. I updated from version 2.3.0d7.

**Comment by Mieze** [comment]
Not a driver problem because 2.3.0 is identical to 2.3.0d7. Only the version number is different.

**Comment by chromer030** [comment]
I tried version 2.3.0d7 , 2.3.0 , and 2.4.0d5 on Catalina 10.15.6 , via latest OpenCore , Not Working !!!!!!!!
Skylake platform with RTL8111/8168B.
Working Great and Perfectly with 2.2.2.
