### ISSUE TITLE
Is It support Big sur?

### ISSUE THREAD

**Issue by chaemoong** [Mieze/RTL8111_driver_for_OS_X#50]

**Comment by Mieze** [comment]
I see no reason why it shouldn't.

**Comment by rediffusion** [comment]
@Mieze 

 Bro, not working on Big Sur 11.1
**MB**: P8H61-M LX3 R2.0

I use _oldest_ version `RealtekRTL8111 V2.2.2`. Works fine❗🚀

**Comment by Mieze** [comment]
I tested the latest development version with Big Sur a few days ago and can confirm that it's working as expected. In case you've got issues, please fix your system because it's not the driver which is responsible for your problem.
