### ISSUE TITLE
Very low download Speed

### ISSUE THREAD

**Issue by anubhaavspark** [Mieze/RTL8111_driver_for_OS_X#58]
I have latest version of Kext installed. But download speed is too low, on the other hand upload speed is good and as accepted. My plan is 300 MBPS. I have attached the screenshot.

![Screenshot 2020-12-10 at 12 55 38 PM](https://user-images.githubusercontent.com/36218159/101734979-26ef3780-3ae7-11eb-9ad8-784867f7cc65.png)

My board is Gigabyte B550 Gaming X V2, and OpenCore 0.6.4

**Comment by nikhil19rathore99** [comment]
in my laptop with BigSurr it doesn't works.
help!!

**Comment by mehmetyukcell** [comment]
> in my laptop with BigSurr it doesn't works.
> help!!

Please, system preferences, networks, ethernet, advanced level, 
![Ekran Resmi 2020-12-23 10 35 31](https://user-images.githubusercontent.com/62822060/102971520-98c57900-450a-11eb-9a23-7f24af9ecee9.png)

**Comment by Mieze** [comment]
Please read the instructions because you haven't. Otherwise you wouldn't post support requests here on GitHub.

**Comment by anubhaavspark** [comment]
My original request was for "Slow Download Speed" in BigSur. It worked perfectly in Catalina. So, yes I have read instructions.
