### ISSUE TITLE
very slow upload transfer speeds that eventually fail...

### ISSUE THREAD

**Issue by hoondi** [Mieze/RTL8111_driver_for_OS_X#6]
Hi,
Really love your work and am enjoying your RTK2.0 driver on my X58 mobo.

I got my hands on an old GB EP45UD3P which has 2 x RTK 8111C so I installed your driver.

I'm experiencing very slow upload speeds. (download speeds are terrific! > 100MB/sec.)

Mac OS X 10.10.5
C2D @ 3.0GHz
8GB DDR2

I've also connected to the GB EP45UD3P using a 2008 MacPro and SMB. It too is very slow to download anything from the GB EP45UD3P (uploading from the 2008 MacPro to the GB EP45UD3P is very fast though)

<img width="423" alt="uploadslow" src="https://cloud.githubusercontent.com/assets/598485/12070064/e20869ea-b0b0-11e5-92ee-e06a67d9e5b5.png">

Back on the GB EP45UD3P machine and attempting to upload to my X58 mobo, the transfer starts off quickly, but almost immediately slows down to a crawl of only double digit kilobytes per second.
Eventually, I'll see an error dialog box:
![error](https://cloud.githubusercontent.com/assets/598485/12070077/8efae3f8-b0b1-11e5-9a04-69f3fc020bd3.png)

Console.app shows many lines of:
>1/01/2016 5:58:34.000 pm kernel[0]: smb_iod_reconnect: Reconnected share FILES with server HacProServer._smb._tcp.local
1/01/2016 5:58:35.000 pm kernel[0]: smb_fid_get_kernel_fid: No SMB 2/3 fid found for fid c7ebefe2d8a595de

where the last hexadecimal value is always different.

I'm aware of you mentioning and SMB issue with Broadcom/RTLK Nics but I've also tested with AFP and experience the same issue.

Here are the kexts I'm running:
>Server:~ madmin$ kextstat
Index Refs Address            Size       Wired      Name (Version) <Linked Against>
    1   67 0xffffff7f80a0f000 0x8c50     0x8c50     com.apple.kpi.bsd (14.5.0)
    2    7 0xffffff7f81017000 0x28c0     0x28c0     com.apple.kpi.dsep (14.5.0)
    3   83 0xffffff7f80a18000 0x20500    0x20500    com.apple.kpi.iokit (14.5.0)
    4   89 0xffffff7f80a03000 0xbf50     0xbf50     com.apple.kpi.libkern (14.5.0)
    5   77 0xffffff7f80a00000 0x2d50     0x2d50     com.apple.kpi.mach (14.5.0)
    6   42 0xffffff7f80a3e000 0x8590     0x8590     com.apple.kpi.private (14.5.0)
    7   58 0xffffff7f80a39000 0x4900     0x4900     com.apple.kpi.unsupported (14.5.0)
    8    3 0xffffff7f8101d000 0xa0000    0xa0000    com.apple.kec.corecrypto (1.0) <7 6 5 4 3 1>
    9    0 0xffffff7f81155000 0xc000     0xc000     com.apple.kec.pthread (1) <7 6 5 4 1>
   10    1 0xffffff7f8164a000 0x9000     0x9000     com.apple.kec.Libm (1) <4>
   11   12 0xffffff7f81adf000 0x9000     0x9000     com.apple.iokit.IOACPIFamily (1.4) <7 6 4 3>
   12   20 0xffffff7f80d98000 0x34000    0x34000    com.apple.iokit.IOPCIFamily (2.9) <7 6 5 4 3>
   13    1 0xffffff7f827d2000 0x65000    0x65000    com.apple.driver.AppleACPIPlatform (3.1) <12 11 7 6 5 4 3 1>
   14    0 0xffffff7f81635000 0x2000     0x2000     org.tgwbd.driver.NullCPUPowerManagement (1.0.0d2) <7 4 3>
   15    1 0xffffff7f817fb000 0xb000     0xb000     com.apple.driver.AppleFDEKeyStore (28.30) <8 7 6 5 4 3 1>
   16    1 0xffffff7f81ad8000 0x7000     0x7000     com.apple.iokit.IOReportFamily (31) <5 4 3>
   17    4 0xffffff7f80a47000 0x2e000    0x2e000    com.apple.iokit.IOStorageFamily (2.0) <7 6 5 4 3 1>
   18    0 0xffffff7f81b58000 0x1e000    0x1e000    com.apple.driver.DiskImages (398) <17 7 6 5 4 3 1>
   19    0 0xffffff7f81eea000 0x1d000    0x1d000    org.netkas.driver.FakeSMC (1328) <11 7 5 4 3 1>
   20    1 0xffffff7f823aa000 0xf000     0xf000     com.apple.driver.AppleCredentialManager (1.0) <7 5 4 3 1>
   21    2 0xffffff7f81122000 0xd000     0xd000     com.apple.driver.AppleMobileFileIntegrity (1.0.5) <7 6 5 4 3 2 1>
   22    0 0xffffff7f823b9000 0x23000    0x23000    com.apple.driver.AppleKeyStore (2) <21 20 8 7 6 5 4 3 1>
   23    0 0xffffff7f82437000 0x2b000    0x2b000    com.apple.driver.AppleIntelCPUPowerManagement (218.0.0) <7 6 5 4 3 1>
   24    0 0xffffff7f8101a000 0x2000     0x2000     com.apple.security.TMSafetyNet (8) <7 6 5 4 2 1>
   25    2 0xffffff7f8112f000 0x5000     0x5000     com.apple.kext.AppleMatch (1.0.0d1) <4 1>
   26    1 0xffffff7f81134000 0x17000    0x17000    com.apple.security.sandbox (300.0) <25 21 7 6 5 4 3 2 1>
   27    0 0xffffff7f8114b000 0x9000     0x9000     com.apple.security.quarantine (3) <26 25 7 6 5 4 2 1>
   28    0 0xffffff7f82848000 0x8000     0x8000     com.apple.nke.applicationfirewall (161) <7 6 5 4 3 1>
   29    0 0xffffff7f827a5000 0x3000     0x3000     com.apple.driver.AppleAPIC (1.7) <4 3>
   30    0 0xffffff7f822d3000 0x4000     0x4000     com.apple.driver.AppleSMBIOS (2.1) <7 4 3>
   31    0 0xffffff7f824b6000 0x3000     0x3000     com.apple.driver.AppleHPET (1.8) <11 7 5 4 3>
   32    0 0xffffff7f82301000 0x8000     0x8000     com.apple.driver.AppleRTC (2.0) <11 5 4 3 1>
   33    1 0xffffff7f8252b000 0x5000     0x5000     com.apple.driver.AppleEFIRuntime (2.0) <7 6 5 4 3>
   34    1 0xffffff7f82530000 0xb000     0xb000     com.apple.driver.AppleEFINVRAM (2.0) <33 7 6 5 4 3 1>
   35    2 0xffffff7f81806000 0x8a000    0x8a000    com.apple.iokit.IOHIDFamily (2.0.0) <15 7 6 5 4 3 2 1>
   36    0 0xffffff7f82841000 0x4000     0x4000     com.apple.driver.AppleACPIButtons (3.1) <35 13 11 7 6 5 4 3 1>
   37    6 0xffffff7f81773000 0x71000    0x71000    com.apple.iokit.IOUSBFamily (720.4.4) <12 7 5 4 3 1>
   38    0 0xffffff7f818e2000 0x10000    0x10000    com.apple.driver.AppleUSBUHCI (656.4.1) <37 12 7 5 4 3 1>
   39    0 0xffffff7f81936000 0x19000    0x19000    com.apple.driver.AppleUSBEHCI (705.4.14) <37 12 7 5 4 3 1>
   40    2 0xffffff7f81d46000 0x19000    0x19000    com.apple.iokit.IOAHCIFamily (2.7.5) <5 4 3 1>
   41    0 0xffffff7f827aa000 0x1b000    0x1b000    com.apple.driver.AppleAHCIPort (3.1.2) <40 12 5 4 3 1>
   42    2 0xffffff7f81675000 0x84000    0x84000    com.apple.iokit.IOFireWireFamily (4.5.8) <5 4 3 1>
   43    0 0xffffff7f81bb7000 0x27000    0x27000    com.apple.driver.AppleFWOHCI (5.5.2) <42 12 7 6 5 4 3 1>
   44    0 0xffffff7f81913000 0x1c000    0x1c000    com.apple.driver.AppleUSBHub (705.4.2) <37 5 4 3 1>
   45    3 0xffffff7f81734000 0x33000    0x33000    com.apple.iokit.IONetworkingFamily (3.2) <7 6 5 4 3 1>
   46    0 0xffffff7f8200b000 0xa000     0xa000     com.apple.BootCache (36) <7 6 5 4 3 1>
   47    0 0xffffff7f8277e000 0x6000     0x6000     com.apple.AppleFSCompression.AppleFSCompressionTypeZlib (1.0.0) <6 4 3 2 1>
   48    0 0xffffff7f82786000 0x3000     0x3000     com.apple.AppleFSCompression.AppleFSCompressionTypeDataless (1.0.0d1) <7 6 4 3 2 1>
   50    0 0xffffff7f818a4000 0xa000     0xa000     com.apple.driver.AppleUSBComposite (705.4.9) <37 4 3 1>
   51    0 0xffffff7f8189a000 0xa000     0xa000     com.apple.iokit.IOUSBHIDDriver (705.4.0) <37 35 5 4 3 1>
   53    0 0xffffff7f81d79000 0x18000    0x18000    com.apple.iokit.IOAHCIBlockStorage (2.7.1) <40 17 6 5 4 3 1>
   54    0 0xffffff7f82022000 0x3000     0x3000     com.apple.driver.XsanFilter (404) <17 5 4 3 1>
   55    0 0xffffff7f80d56000 0x31000    0x31000    com.apple.iokit.IOSCSIArchitectureModelFamily (3.7.5) <5 4 3 1>
   57    8 0xffffff7f81165000 0x47000    0x47000    com.apple.iokit.IOGraphicsFamily (2.4.1) <12 7 5 4 3 1>
   58    3 0xffffff7f811ac000 0x10000    0x10000    com.apple.iokit.IONDRVSupport (2.4.1) <57 12 7 5 4 3>
   59    1 0xffffff7f811bc000 0x7000     0x7000     com.apple.AppleGraphicsDeviceControl (3.10.25) <7 6 5 4 3 1>
   60    2 0xffffff7f811c3000 0x28d000   0x28d000   com.apple.nvidia.driver.NVDAResman (10.0.4) <59 58 57 12 5 4 3 1>
   61    1 0xffffff7f81a76000 0x4000     0x4000     com.apple.iokit.IOSMBusFamily (1.1) <5 4 3>
   62    1 0xffffff7f822c2000 0x11000    0x11000    com.apple.driver.AppleSMBusController (1.0.13d1) <61 12 11 5 4 3>
   63    0 0xffffff7f8236d000 0xe000     0xe000     com.apple.driver.AppleMCCSControl (1.2.12) <62 57 12 11 7 5 4 3 1>
   64    0 0xffffff7f82180000 0x5000     0x5000     com.apple.driver.AppleUpstreamUserClient (3.6.1) <57 12 11 7 5 4 3 1>
   65    2 0xffffff7f8207c000 0x78000    0x78000    com.apple.vecLib.kext (1.2.0) <10 6 5 4 3>
   66    3 0xffffff7f820f4000 0x38000    0x38000    com.apple.iokit.IOAudioFamily (203.3) <65 5 4 3 1>
   67    2 0xffffff7f824e9000 0xf000     0xf000     com.apple.iokit.IOHDAFamily (272.18.3) <5 4 3 1>
   68    1 0xffffff7f824fc000 0x1c000    0x1c000    com.apple.driver.AppleHDAController (272.18.3) <67 66 57 12 7 6 5 4 3 1>
   69    0 0xffffff7f81450000 0x1e5000   0x1e5000   com.apple.nvidia.driver.NVDAGF100Hal (10.0.4) <60 12 4 3>
   70    1 0xffffff7f81d9e000 0x7d000    0x7d000    com.apple.iokit.IOAcceleratorFamily2 (156.16) <57 12 7 6 5 4 3 1>
   71    0 0xffffff7f81e1b000 0x97000    0x97000    com.apple.GeForce (10.0.4) <70 60 58 57 12 7 5 4 3 1>
   72    2 0xffffff7f81b06000 0x1c000    0x1c000    com.apple.driver.AppleSMC (3.1.9) <11 7 5 4 3 1>
   73    0 0xffffff7f81ba7000 0x10000    0x10000    com.apple.iokit.IOFireWireIP (2.2.6) <45 42 5 4 3 1>
   76    0 0xffffff7f817f8000 0x3000     0x3000     com.apple.iokit.IOUSBUserClient (705.4.0) <37 7 5 4 3 1>
   77    1 0xffffff7f81a7a000 0x5000     0x5000     com.apple.iokit.IOSlowAdaptiveClockingFamily (1.0.0) <7 6 5 4 3 1>
   78    0 0xffffff7f823e3000 0x2000     0x2000     com.apple.driver.AppleIntelSlowAdaptiveClocking (4.0.0) <77 4 3>
   79    0 0xffffff7f822bf000 0x3000     0x3000     com.apple.driver.AppleSMBusPCI (1.0.12d1) <12 5 4 3>
   80    2 0xffffff7f81ae8000 0xa000     0xa000     com.apple.driver.IOPlatformPluginFamily (5.9.1d7) <11 7 6 5 4 3>
   81    1 0xffffff7f81af2000 0x14000    0x14000    com.apple.driver.IOPlatformPluginLegacy (1.0.0) <80 11 7 6 5 4 3>
   82    0 0xffffff7f81b22000 0x10000    0x10000    com.apple.driver.ACPI_SMC_PlatformPlugin (1.0.0) <81 80 72 12 11 7 6 5 4 3>
   83    0 0xffffff7f82478000 0xb000     0xb000     com.apple.driver.AppleHV (1) <7 6 5 4 3 1>
   84    0 0xffffff7f82473000 0x3000     0x3000     com.apple.driver.AppleHWAccess (1) <7 5 4 3>
   85    0 0xffffff7f81f07000 0x5000     0x5000     com.apple.Dont_Steal_Mac_OS_X (7.0.0) <72 7 4 3 1>
   86    0 0xffffff7f81c37000 0xbd000    0xbd000    com.apple.iokit.IOBluetoothFamily (4.3.6f3) <16 7 5 4 3 1>
   87    0 0xffffff7f82359000 0x4000     0x4000     com.apple.driver.AppleOSXWatchdog (1) <12 7 6 5 4 3 1>
   88    0 0xffffff7f81a61000 0x15000    0x15000    com.apple.iokit.IOSurface (97.4) <7 5 4 3 1>
   89    0 0xffffff7f81767000 0x6000     0x6000     com.apple.iokit.IOUserEthernet (1.0.1) <45 6 5 4 3 1>
   90    1 0xffffff7f80a75000 0x36c      0x36c      net.lundman.kernel.dependencies.1.4.5 (12.5.0)
   91    1 0xffffff7f80a76000 0x37000    0x37000    net.lundman.spl (1.4.5) <90 7 5 4 3 1>
   92    1 0xffffff7f80aad000 0x23c000   0x23c000   net.lundman.zfs (1.4.5) <91 17 7 5 4 3 1>
   93    1 0xffffff7f82518000 0x13000    0x13000    com.apple.kext.OSvKernDSPLib (1.15) <5 4>
   94    1 0xffffff7f8253b000 0x13b000   0x13b000   com.apple.driver.DspFuncLib (272.18.3) <93 66 65 34 6 5 4 3 1>
   95    0 0xffffff7f82676000 0xab000    0xab000    com.apple.driver.AppleHDA (272.18.3) <94 68 67 66 58 57 6 5 4 3 1>
   97    1 0xffffff7f81c12000 0x11000    0x11000    com.apple.iokit.IOSerialFamily (11) <7 6 5 4 3 1>
   98    0 0xffffff7f81c23000 0xa000     0xa000     com.apple.iokit.IOBluetoothSerialManager (4.3.6f3) <97 7 5 4 3 1>
   99    2 0xffffff7f810bd000 0x5000     0x5000     com.apple.kext.triggers (1.0) <7 6 5 4 3 1>
  100    0 0xffffff7f82017000 0x9000     0x9000     com.apple.filesystems.autofs (3.0) <99 7 6 5 4 3 1>
  101    0 0xffffff7f82852000 0x70000    0x70000    com.insanelymac.RealtekRTL8111 (2.1.0d1) <45 12 5 4 3 1>
  103    0 0xffffff7f8246a000 0x5000     0x5000     com.apple.driver.AppleHWSensor (1.9.5d0) <5 4 3>
  107    0 0xffffff7f828c2000 0x59000    0x59000    com.apple.filesystems.smbfs (3.0.2) <99 8 7 6 5 4 3 1>
Server:~ madmin$

Here's the output of netstat -s

>Server:~ madmin$ netstat -s
tcp:
	226578 packets sent
		100510 data packets (167602278 bytes)
		40440 data packets (7010117 bytes) retransmitted
		0 resends initiated by MTU discovery
		83134 ack-only packets (2 delayed)
		0 URG only packets
		0 window probe packets
		2244 window update packets
		250 control packets
		0 data packets sent after flow control
		0 checksummed in software
			0 segments (0 bytes) over IPv4
			0 segments (0 bytes) over IPv6
	747080 packets received
		79166 acks (for 171828496 bytes)
		70686 duplicate acks
		0 acks for unsent data
		590015 packets (834745334 bytes) received in-sequence
		56 completely duplicate packets (6625 bytes)
		0 old duplicate packets
		0 received packets dropped due to low memory
		0 packets with some dup. data (0 bytes duped)
		479 out-of-order packets (678163 bytes)
		0 packets (0 bytes) of data after window
		0 window probes
		13112 window update packets
		19 packets received after close
		0 bad resets
		0 discarded for bad checksums
		0 checksummed in software
			0 segments (0 bytes) over IPv4
			0 segments (0 bytes) over IPv6
		0 discarded for bad header offset fields
		0 discarded because packet too short
	96 connection requests
	102 connection accepts
	1 bad connection attempt
	0 listen queue overflows
	162 connections established (including accepts)
	205 connections closed (including 24 drops)
		4 connections updated cached RTT on close
		4 connections updated cached RTT variance on close
		4 connections updated cached ssthresh on close
	0 embryonic connections dropped
	653468 segments updated rtt (of 82507 attempts)
	1557 retransmit timeouts
		0 connections dropped by rexmit timeout
		0 connections dropped after retransmitting FIN
	0 persist timeouts
		0 connections dropped by persist timeout
	0 keepalive timeouts
		0 keepalive probes sent
		0 connections dropped by keepalive
	1315 correct ACK header predictions
	583554 correct data packet header predictions
	12937 SACK recovery episodes
	37330 segment rexmits in SACK recovery episodes
	447960 byte rexmits in SACK recovery episodes
	105263 SACK options (SACK blocks) received
	479 SACK options (SACK blocks) sent
	0 SACK scoreboard overflow
	0 LRO coalesced packets
		0 times LRO flow table was full
		0 collisions in LRO flow table
		0 times LRO coalesced 2 packets
		0 times LRO coalesced 3 or 4 packets
		0 times LRO coalesced 5 or more packets
	25820 limited transmits done
	194 early retransmits done
	5091 times cumulative ack advanced along with SACK
	4 probe timeouts
		2 times retransmit timeout triggered after probe
		0 times fast recovery after tail loss
		1 time recovered last packet 
	0 connections negotiated ECN
		0 times congestion notification was sent using ECE
		0 times CWR was sent in response to ECE
	3 times packet reordering was detected on a connection
		50 times transmitted packets were reordered
		6667 times fast recovery was delayed to handle reordering
		50 times retransmission was avoided by delaying recovery
		0 retransmissions not needed 
udp:
	412 datagrams received
		0 with incomplete header
		0 with bad data length field
		0 with bad checksum
		0 with no checksum
		0 checksummed in software
			0 datagrams (0 bytes) over IPv4
			0 datagrams (0 bytes) over IPv6
		14 dropped due to no socket
		0 broadcast/multicast datagrams undelivered
		0 times multicast source filter matched
		0 dropped due to full socket buffers
		0 not for hashed pcb
		398 delivered
	269 datagrams output
		58 checksummed in software
			0 datagrams (0 bytes) over IPv4
			58 datagrams (12150 bytes) over IPv6
ip:
	747318 total packets received
		0 bad header checksums
		0 headers (0 bytes) checksummed in software
		0 with size smaller than minimum
		0 with data size < data length
		188 with data size > data length
			0 packets forced to software checksum
		0 with ip length > max ip packet size
		0 with header length < data size
		0 with data length < header length
		0 with bad options
		0 with incorrect version number
		0 fragments received
			0 dropped (dup or out of space)
			0 dropped after timeout
			0 reassembled ok
		747254 packets for this host
		22 packets for unknown/unsupported protocol
		0 packets forwarded (0 packets fast forwarded)
		0 packets not forwardable
		42 packets received for unknown multicast group
		0 redirects sent
	226774 packets sent from this host
		0 packets sent with fabricated ip header
		0 output packets dropped due to no bufs, etc.
		0 output packets discarded due to no route
		0 output datagrams fragmented
		0 fragments created
		0 datagrams that can't be fragmented
		0 tunneling packets that can't find gif
		0 datagrams with bad address in header
		0 packets dropped due to no bufs for control data
		70 headers (1448 bytes) checksummed in software
icmp:
	14 calls to icmp_error
	0 errors not generated 'cuz old message was icmp
	Output histogram:
		destination unreachable: 14
	0 messages with bad code fields
	0 messages < minimum length
	0 bad checksums
	0 messages with bad length
	0 multicast echo requests ignored
	0 multicast timestamp requests ignored
	Input histogram:
		destination unreachable: 12
	0 message responses generated
	ICMP address mask responses are disabled
igmp:
	20 messages received
	0 messages received with too few bytes
	0 messages received with wrong TTL
	0 messages received with bad checksum
	0 V1/V2 membership queries received
	10 V3 membership queries received
	0 membership queries received with invalid field(s)
	10 general queries received
	0 group queries received
	0 group-source queries received
	0 group-source queries dropped
	10 membership reports received
	10 membership reports received with invalid field(s)
	0 membership reports received for groups to which we belong
	0 V3 reports received without Router Alert
	12 membership reports sent
ipsec:
	0 inbound packets processed successfully
	0 inbound packets violated process security policy
	0 inbound packets with no SA available
	0 invalid inbound packets
	0 inbound packets failed due to insufficient memory
	0 inbound packets failed getting SPI
	0 inbound packets failed on AH replay check
	0 inbound packets failed on ESP replay check
	0 inbound packets considered authentic
	0 inbound packets failed on authentication
	0 outbound packets processed successfully
	0 outbound packets violated process security policy
	0 outbound packets with no SA available
	0 invalid outbound packets
	0 outbound packets failed due to insufficient memory
	0 outbound packets with no route
arp:
	8 ARP requests sent
	33 ARP replies sent
	0 ARP announcements sent
	70 ARP requests received
	8 ARP replies received
	78 total ARP packets received
	0 ARP conflict probes sent
	0 invalid ARP resolve requests
	0 total packets dropped due to lack of memory
	7 total packets dropped due to no ARP entry
	0 total packets dropped during ARP entry removal
	3 ARP entries timed out
	0 Duplicate IPs seen
mptcp:
	0 data packets sent
	0 data bytes sent
	0 data packets received
	0 data bytes received
	0 packets with an invalid MPCAP option
	0 packets with an invalid MPJOIN option
	0 times primary subflow fell back to TCP
	0 times secondary subflow fell back to TCP
	0 DSS option drops
	0 other invalid MPTCP options
	0 times the MPTCP subflow window was reduced
	0 bad DSS checksums
	0 times received out of order data 
	0 subflow switches
ip6:
	280 total packets received
		0 with size smaller than minimum
		0 with data size < data length
		0 with data size > data length
			0 packets forced to software checksum
		0 with bad options
		0 with incorrect version number
		0 fragments received
			0 dropped (dup or out of space)
			0 dropped after timeout
			0 exceeded limit
			0 reassembled ok
		248 packets for this host
		0 packets forwarded
		18 packets not forwardable
		0 redirects sent
		18 multicast packets which we don't join
		0 packets whose headers are not continuous
		0 tunneling packets that can't find gif
		0 packets discarded due to too may headers
		0 forward cache hit
		0 forward cache miss
		0 packets dropped due to no bufs for control data
	177 packets sent from this host
		0 packets sent with fabricated ip header
		0 output packets dropped due to no bufs, etc.
		0 output packets discarded due to no route
		0 output datagrams fragmented
		0 fragments created
		0 datagrams that can't be fragmented
		0 packets that violated scope rules
	Input histogram:
		TCP: 135
		UDP: 113
		ICMP6: 32
	Mbuf statistics:
		25 one mbuf
		two or more mbuf:
			lo0= 58
		197 one ext mbuf
		0 two or more ext mbuf
		0 failures of source address selection
icmp6:
	0 calls to icmp_error
	0 errors not generated because old message was icmp error or so
	0 errors not generated because rate limitation
	Output histogram:
		router solicitation: 5
		neighbor solicitation: 8
		neighbor advertisement: 7
		MLDv2 listener report: 3
	0 messages with bad code fields
	0 messages < minimum length
	0 bad checksums
	0 messages with bad length
	Input histogram:
		neighbor solicitation: 7
		neighbor advertisement: 7
	Histogram of error messages to be generated:
		0 no route
		0 administratively prohibited
		0 beyond scope
		0 address unreachable
		0 port unreachable
		0 packet too big
		0 time exceed transit
		0 time exceed reassembly
		0 erroneous header field
		0 unrecognized next header
		0 unrecognized option
		0 redirect
		0 unknown
	0 message responses generated
	0 messages with too many ND options
	0 messages with bad ND options
	0 bad neighbor solicitation messages
	7 bad neighbor advertisement messages
	0 bad router solicitation messages
	0 bad router advertisement messages
	0 bad redirect messages
	0 path MTU changes
ipsec6:
	0 inbound packets processed successfully
	0 inbound packets violated process security policy
	0 inbound packets with no SA available
	0 invalid inbound packets
	0 inbound packets failed due to insufficient memory
	0 inbound packets failed getting SPI
	0 inbound packets failed on AH replay check
	0 inbound packets failed on ESP replay check
	0 inbound packets considered authentic
	0 inbound packets failed on authentication
	0 outbound packets processed successfully
	0 outbound packets violated process security policy
	0 outbound packets with no SA available
	0 invalid outbound packets
	0 outbound packets failed due to insufficient memory
	0 outbound packets with no route
rip6:
	0 messages received
	0 checksum calcurations on inbound
	0 messages with bad checksum
	0 messages dropped due to no socket
	0 multicast messages dropped due to no socket
	0 messages dropped due to full socket buffers
	0 delivered
	0 datagrams output
pfkey:
	0 requests sent to userland
	0 bytes sent to userland
	0 messages with invalid length field
	0 messages with invalid version field
	0 messages with invalid message type field
	0 messages too short
	0 messages with memory allocation failure
	0 messages with duplicate extension
	0 messages with invalid extension type
	0 messages with invalid sa type
	0 messages with invalid address extension
	0 requests sent from userland
	0 bytes sent from userland
	0 messages toward single socket
	0 messages toward all sockets
	0 messages toward registered sockets
	0 messages with memory allocation failure
kevt:
	7 current kernel control sockets
	7 kernel control generation count
	0 bad vendor failures
	74 message too big failures
	0 out of memeory failures
	0 messages dropped due to full socket buffers
	84 message posteds
kctl:
	0 total kernel control modules registered
	10 current kernel control modules registered
	14 current kernel control sockets
	676 kernel control generation count
	340 connection attempts
	0 connection failures
	13 send failures
	0 send list failures
	15 enqueus failures
	15 packets dropped due to full socket buffers
Server:~ madmin$>

I also disabled EEE via the plist which has not helped.

Any suggestions?

Regards,

**Comment by hoondi** [comment]
Just letting you know that I installed Lnx2Mac's Realtek RTL81xx Driver and all is well – as expected download and upload speeds.

So that suggests there's nothing obviously wrong with my environment/setup.

Regards,

**Comment by Mieze** [comment]
There is something wrong with your setup because you probably have a serious problem with interrupt latency.
