### ISSUE TITLE
Is RTL-8110SC/8169SC supported?

### ISSUE THREAD

**Issue by rafaelmaeuer** [Mieze/RTL8111_driver_for_OS_X#64]
Hi I was wondering if RTL-8110SC/8169SC is supported by this kext too?
It seems to be very similar or the predecessor to RTL8111?

**Comment by Mieze** [comment]
As PCI devices are incapable of performing DMA operations with 64 Bit addresses, a completely different driver architecture would be required. By the way, these NICs are legacy hardware and I wouldn't even think about investing time and money to support them.
