### ISSUE TITLE
Does not automatically connect to 100BASE-T networks

### ISSUE THREAD

**Issue by hectorgrom** [Mieze/RTL8111_driver_for_OS_X#66]
First of all, congratulations on your beautiful work ...

I found a small bug that I would like to share ...

I use the "Realtek RTL8168F / 8111F PCI Express Gigabit Ethernet" network card on the ASUS H-61M-A, using the old drivers, the network works perfect, however, using the latest driver v2.4.0, the the network works automatically only on 1000BASE-T networks, it does not automatically select the 100BASE-T standard, requiring manual selection of the "oldest" standard for it to work ....

Grateful

**Comment by Mieze** [comment]
Resolved in 2.4.2d0
