### ISSUE TITLE
Intermittent SSL errors

### ISSUE THREAD

**Issue by kibiz0r** [Mieze/RTL8111_driver_for_OS_X#70]
This may only be indirectly related to your project, but I don't know enough about network adapters to say, so please forgive my ignorance.

## Using automatic network adapter settings or 1000baseT:

Often, but not every time (feels about 20% of the time), when I download via (built-in, system) curl, I get: `curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0`

Example:
```
> curl -Lo foo.dmg https://dl.google.com/dl/android/studio/install/4.2.1.0/android-studio-ide-202.7351085-mac.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  936M    2 20.8M    0     0  20.9M      0  0:00:44 --:--:--  0:00:44 20.9M
curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0
```

I tried checking out whether curl via homebrew would work better, but I get similar results:

```
> /usr/local/Cellar/curl/7.77.0/bin/curl -Lo foo.dmg https://dl.google.com/dl/android/studio/install/4.2.1.0/android-studio-ide-202.7351085-mac.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  936M    0 8863k    0     0  9065k      0  0:01:45 --:--:--  0:01:45 9081k
curl: (56) OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
```

Similar story in Chrome: Often, but not every time, when I download a file via Chrome, I get "Failed - Network error".

My example URL in this case could be `https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip`

## If I put the speed down to 100baseTX:

...then with a lower speed, I get no such errors. But... that's not the speed that Ubuntu reports, and the mobo's config UI describes it as:
- Realtek PCIe GBE Family Controller
- Driver name: Realtek UEFI UNDI Driver
- Driver version: 2.042

...so I'd rather not throttle it down to 100baseTX if I can help it -- besides which it doesn't make any sense to me that transmission speed would have anything to do with SSL, but here I am.

For reference, Ubuntu describes the adapter as:
- RTL8111/8168/8411 rev 16

OS-level datetime was my first thought, but that seems to be syncing up perfectly, and I can't get past the fact that the problem has never occurred when I have the adapter set to 100baseTX.

I've messed around with flow control setting, but that doesn't seem to make any difference. Again though, I am ignorant in this domain.

This has been happening since a first-time install of Big Sur, 11.3, about 2 weeks ago, and I've since updated to 11.4 with no improvement. I'm using version 2.4.2 of your driver.

Any thoughts at all would be appreciated.

**Comment by Mieze** [comment]
Read instructions and post in the IM forum!
