### ISSUE TITLE
Not working on Ventura beta

### ISSUE THREAD

**Issue by rul3v01d3r** [Mieze/RTL8111_driver_for_OS_X#75]
![image](https://user-images.githubusercontent.com/45416516/174444301-dade7d1b-ad52-48dd-ad2d-eaddcfb552c5.png)
Not working on Ventura beta, but kext is loaded and pic device is shown  in Hackintool. 
![image](https://user-images.githubusercontent.com/45416516/174444413-a539c629-d816-4b60-8090-a84c7d1c3352.png)
![image](https://user-images.githubusercontent.com/45416516/174444434-b8b8116d-61ea-47a1-9261-be2cfb7c03cd.png)
![image](https://user-images.githubusercontent.com/45416516/174444468-abe734af-cc31-4b55-ac5a-497425d6fcad.png)

**Comment by Mieze** [comment]
First, this is the wrong place to post. Second, what does an USB device have to do with the driver? Check your system and/or post in the right place.

**Comment by rul3v01d3r** [comment]
> First, this is the wrong place to post. Second, what does an USB device have to do with the driver? Check your system and/or post in the right place.

i m showing the ethernet devices not the usb device and i thought this is the place to open the issue if not i m sorry for that, but i want to show u that ur kext is loaded but not working on ventura beta
my specs are:
cpu 5800x
mobo msi x570 a pro
ethernet realtek8111/8168
os ventura beta
tried ur latest version i.e. 2.4.2

**Comment by wolter8** [comment]
> > First, this is the wrong place to post. Second, what does an USB device have to do with the driver? Check your system and/or post in the right place.
> 
> i m showing the ethernet devices not the usb device and i thought this is the place to open the issue if not i m sorry for that, but i want to show u that ur kext is loaded but not working on ventura beta my specs are: cpu 5800x mobo msi x570 a pro ethernet realtek8111/8168 os ventura beta tried ur latest version i.e. 2.4.2

Did you solve this? I have the same mono and the same problem, I've tried all versions and nothing working.

**Comment by rul3v01d3r** [comment]
for msi u need pci=0x80000000 bootargs and latest patch
