### ISSUE TITLE
Connection not working (Link status: Inactive) on Yosemite and El Capitan

### ISSUE THREAD

**Issue by duksi1993** [Mieze/RTL8111_driver_for_OS_X#8]
This driver perfectly worked until update to Yosemite. It also **doesn't work** on El Capitan.
I have RTL8168GR chip on my board, and it is recognized by both OS X Yosemite and El Capitan as RTL8168G (I got correct Mac address of chip), but there is no connection. I got **no IP address** (field is blank), Link status is always **Inactive**, and Link speed is always: **0Mb/s**.
I tried to full power off computer, even unplug it from power cord, but it is still not working.
I also tried to set PXE to CSM in UEFI, disable FIX_LAN in Clover, but still I got no luck.

Ethernet [RealtekRTL8111]: EEE support enabled.
Ethernet [RealtekRTL8111]: TCP/IPv4 segmentation offload enabled.
Ethernet [RealtekRTL8111]: TCP/IPv6 checksum offload enabled.
Ethernet [RealtekRTL8111]: Using interrupt mitigate value 0xcf68.
Ethernet [RealtekRTL8111]: RTL8168G/8111G: (Chipset 20) at 0xffffff81c645b000, d0:50:99:48:9e:79

en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    options=6b<RXCSUM,TXCSUM,VLAN_HWTAGGING,TSO4,TS06>
    ether d0:50:99:48:9e:79
    nd6 options=1<PERFORMNUD>
    media: autoselect (<unknown type>)
    status: inactive

**Comment by Mieze** [comment]
The driver works perfectly under Yosemite as well as under El Capitan, it's your system which is broken. Please fix it. If you need further assistance, please ask for help in the driver's thread in the forum: http://www.insanelymac.com/forum/topic/287161-new-driver-for-realtek-rtl8111/#entry1898032
