### ISSUE TITLE
Network Freezes When Using RTL8111_driver_for_OS_X with Specific kexts from USBToolBox

### ISSUE THREAD

**Issue by holoto** [Mieze/RTL8111_driver_for_OS_X#86]
#### Project:
- **RTL8111_driver_for_OS_X**: [Link to the project](https://github.com/Mieze/RTL8111_driver_for_OS_X)
- **USBToolBox**: [Link to the project](https://github.com/USBToolBox/kext)

#### Issue Type:
- **Bug Report**

#### Detailed Description:
When using the `RTL8111_driver_for_OS_X` driver in conjunction with the following kexts from the `USBToolBox` project:
- `USBToolBox.kext`
- `UTBMap.kext`
- `UTBDefault.kext`
- `USBMap.kext`

The network connection becomes unresponsive or "freezes" when uploading data. This issue does not occur when using `USBInjectAll.kext` or `USBPorts.kext` generated by Hackintool.

#### Steps to Reproduce:
1. Install the `RTL8111_driver_for_OS_X` driver.
2. Install the following kexts from the `USBToolBox` project:
   - `USBToolBox.kext`
   - `UTBMap.kext`
   - `UTBDefault.kext`
   - `USBMap.kext`
3. Reboot the system.
4. Attempt to upload data over the network.

#### Expected Result:
The network should remain responsive and data should be uploaded without any issues.

#### Actual Result:
The network connection becomes unresponsive or "freezes" during the upload process.

#### Environment Information:
- **Operating System**: Darwin Mac-Pro.local 23.4.0
- **Kernel Version**: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64
- **Architecture**: x86_64
- **Model Name**: Mac Pro
- **Model Identifier**: MacPro7,1
- **Processor Name**: 6-Core Intel Core i5

#### Additional Information:
- The issue does not occur when using `USBInjectAll.kext` or `USBPorts.kext` generated by Hackintool.

#### Related Code or Screenshots:
![Screenshot 2024-11-23 at 06 31 54](https://github.com/user-attachments/assets/0864a806-31bf-4804-913d-a7c46a897997)
![macos](https://github.com/user-attachments/assets/4b6579a7-a236-4d56-8fe6-fffa1a165ac9)

#### good Solutions:

- remove the `USBToolBox` kexts.
- using `USBInjectAll.kext` or `USBPorts.kext` generated by Hackintool.

The solution is to avoid using the RTL8111_driver_for_OS_X driver with the USBToolBox kexts. Instead, use USBInjectAll.kext or USBPorts.kext generated by Hackintool. This configuration ensures that the network remains stable and responsive during data uploads.
---

**Comment by Mieze** [comment]
I don't see any relation between an ethernet driver and the USB subsystem because both systems are completely independent. Besides a misconfigured system the only possible explanation for such a behaviour is that the USB subsystem might block interrupts from being handled preventing the driver from handling network traffic but this is not a bug of the ethernet driver and there is nothing which can be done inside it to resolve the issue. Instead of that, the problem must be solved where it originates from.
